-- CreateEnum
CREATE TYPE "CarStatus" AS ENUM ('CHECKED_IN', 'DIAGNOSIS', 'AWAITING_PARTS', 'IN_SERVICE', 'READY_FOR_PICKUP', 'PICKED_UP', 'CANCELLED');

-- AlterTable
ALTER TABLE "Car" ADD COLUMN     "status" "CarStatus" NOT NULL DEFAULT 'CHECKED_IN';
